# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12task_service.proto\x12\x04task\x1a\x1bgoogle/protobuf/empty.proto\".\n\x04Task\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08\x32\x96\x01\n\x0bTaskService\x12$\n\nCreateTask\x12\n.task.Task\x1a\n.task.Task\x12\x32\n\nGetAllTask\x12\x16.google.protobuf.Empty\x1a\n.task.Task0\x01\x12-\n\x13MarkTaskAsCompleted\x12\n.task.Task\x1a\n.task.Taskb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASK']._serialized_start=57
  _globals['_TASK']._serialized_end=103
  _globals['_TASKSERVICE']._serialized_start=106
  _globals['_TASKSERVICE']._serialized_end=256
# @@protoc_insertion_point(module_scope)
